version: "1"

services:
  java:
    build: .
    image: STO
    container_name: STO
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/STO
      - SPRING_DATASOURCE_USERNAME=STO
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 6060:6060
    depends_on:
      - postgres
    volumes:
      - STO_data:/java/upload

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: STO
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: STO
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  STO_data: null
  postgres_data: null
